{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Train a Pytorch Lightning Image Classifier\n",
    "\n",
    "This example introduces how to train a Pytorch Lightning Module using Ray Train {class}`TorchTrainer <ray.train.torch.TorchTrainer>`. It demonstrates how to train a basic neural network on the MNIST dataset with distributed data parallelism.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: torchmetrics>=0.9 in /home/jtb/anaconda3/lib/python3.10/site-packages (1.3.2)\n",
      "Requirement already satisfied: pytorch_lightning>=1.6 in /home/jtb/anaconda3/lib/python3.10/site-packages (2.2.1)\n",
      "Requirement already satisfied: numpy>1.20.0 in /home/jtb/.local/lib/python3.10/site-packages (from torchmetrics>=0.9) (1.24.1)\n",
      "Requirement already satisfied: packaging>17.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torchmetrics>=0.9) (23.2)\n",
      "Requirement already satisfied: torch>=1.10.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torchmetrics>=0.9) (2.2.2)\n",
      "Requirement already satisfied: lightning-utilities>=0.8.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torchmetrics>=0.9) (0.11.2)\n",
      "Requirement already satisfied: tqdm>=4.57.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from pytorch_lightning>=1.6) (4.65.0)\n",
      "Requirement already satisfied: PyYAML>=5.4 in /home/jtb/anaconda3/lib/python3.10/site-packages (from pytorch_lightning>=1.6) (6.0.1)\n",
      "Requirement already satisfied: fsspec>=2022.5.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from fsspec[http]>=2022.5.0->pytorch_lightning>=1.6) (2024.3.1)\n",
      "Requirement already satisfied: typing-extensions>=4.4.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from pytorch_lightning>=1.6) (4.9.0)\n",
      "Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from fsspec[http]>=2022.5.0->pytorch_lightning>=1.6) (3.9.3)\n",
      "Requirement already satisfied: setuptools in /home/jtb/anaconda3/lib/python3.10/site-packages (from lightning-utilities>=0.8.0->torchmetrics>=0.9) (68.2.2)\n",
      "Requirement already satisfied: filelock in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (3.13.1)\n",
      "Requirement already satisfied: sympy in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (1.12)\n",
      "Requirement already satisfied: networkx in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (3.2.1)\n",
      "Requirement already satisfied: jinja2 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (3.1.3)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (12.1.105)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (12.1.105)\n",
      "Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (12.1.105)\n",
      "Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (8.9.2.26)\n",
      "Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (12.1.3.1)\n",
      "Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (11.0.2.54)\n",
      "Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (10.3.2.106)\n",
      "Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (11.4.5.107)\n",
      "Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (12.1.0.106)\n",
      "Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (2.19.3)\n",
      "Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (12.1.105)\n",
      "Requirement already satisfied: triton==2.2.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch>=1.10.0->torchmetrics>=0.9) (2.2.0)\n",
      "Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/jtb/anaconda3/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.10.0->torchmetrics>=0.9) (12.4.127)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /home/jtb/anaconda3/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning>=1.6) (1.3.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning>=1.6) (23.1.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning>=1.6) (1.4.1)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /home/jtb/anaconda3/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning>=1.6) (6.0.5)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning>=1.6) (1.9.4)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning>=1.6) (4.0.3)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from jinja2->torch>=1.10.0->torchmetrics>=0.9) (2.1.3)\n",
      "Requirement already satisfied: mpmath>=0.19 in /home/jtb/anaconda3/lib/python3.10/site-packages (from sympy->torch>=1.10.0->torchmetrics>=0.9) (1.3.0)\n",
      "Requirement already satisfied: idna>=2.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from yarl<2.0,>=1.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning>=1.6) (3.4)\n",
      "Requirement already satisfied: torchvision in /home/jtb/anaconda3/lib/python3.10/site-packages (0.17.2)\n",
      "Requirement already satisfied: numpy in /home/jtb/.local/lib/python3.10/site-packages (from torchvision) (1.24.1)\n",
      "Requirement already satisfied: torch==2.2.2 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torchvision) (2.2.2)\n",
      "Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torchvision) (10.2.0)\n",
      "Requirement already satisfied: filelock in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (3.13.1)\n",
      "Requirement already satisfied: typing-extensions>=4.8.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (4.9.0)\n",
      "Requirement already satisfied: sympy in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (1.12)\n",
      "Requirement already satisfied: networkx in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (3.2.1)\n",
      "Requirement already satisfied: jinja2 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (3.1.3)\n",
      "Requirement already satisfied: fsspec in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (2024.3.1)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (12.1.105)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (12.1.105)\n",
      "Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (12.1.105)\n",
      "Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (8.9.2.26)\n",
      "Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (12.1.3.1)\n",
      "Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (11.0.2.54)\n",
      "Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (10.3.2.106)\n",
      "Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (11.4.5.107)\n",
      "Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (12.1.0.106)\n",
      "Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (2.19.3)\n",
      "Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (12.1.105)\n",
      "Requirement already satisfied: triton==2.2.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from torch==2.2.2->torchvision) (2.2.0)\n",
      "Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/jtb/anaconda3/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.2->torchvision) (12.4.127)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from jinja2->torch==2.2.2->torchvision) (2.1.3)\n",
      "Requirement already satisfied: mpmath>=0.19 in /home/jtb/anaconda3/lib/python3.10/site-packages (from sympy->torch==2.2.2->torchvision) (1.3.0)\n",
      "Requirement already satisfied: ray in /home/jtb/anaconda3/lib/python3.10/site-packages (2.10.0)\n",
      "Requirement already satisfied: click>=7.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray) (8.1.7)\n",
      "Requirement already satisfied: filelock in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray) (3.13.1)\n",
      "Requirement already satisfied: jsonschema in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray) (4.19.2)\n",
      "Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray) (1.0.8)\n",
      "Requirement already satisfied: packaging in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray) (23.2)\n",
      "Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray) (4.25.3)\n",
      "Requirement already satisfied: pyyaml in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray) (6.0.1)\n",
      "Requirement already satisfied: aiosignal in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray) (1.3.1)\n",
      "Requirement already satisfied: frozenlist in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray) (1.4.1)\n",
      "Requirement already satisfied: requests in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray) (2.31.0)\n",
      "Requirement already satisfied: attrs>=22.2.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from jsonschema->ray) (23.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/jtb/anaconda3/lib/python3.10/site-packages (from jsonschema->ray) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /home/jtb/anaconda3/lib/python3.10/site-packages (from jsonschema->ray) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from jsonschema->ray) (0.10.6)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/jtb/anaconda3/lib/python3.10/site-packages (from requests->ray) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/jtb/anaconda3/lib/python3.10/site-packages (from requests->ray) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from requests->ray) (2.1.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/jtb/anaconda3/lib/python3.10/site-packages (from requests->ray) (2024.2.2)\n",
      "Requirement already satisfied: ray[default] in /home/jtb/anaconda3/lib/python3.10/site-packages (2.10.0)\n",
      "Requirement already satisfied: click>=7.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (8.1.7)\n",
      "Requirement already satisfied: filelock in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (3.13.1)\n",
      "Requirement already satisfied: jsonschema in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (4.19.2)\n",
      "Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (1.0.8)\n",
      "Requirement already satisfied: packaging in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (23.2)\n",
      "Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (4.25.3)\n",
      "Requirement already satisfied: pyyaml in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (6.0.1)\n",
      "Requirement already satisfied: aiosignal in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (1.3.1)\n",
      "Requirement already satisfied: frozenlist in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (1.4.1)\n",
      "Requirement already satisfied: requests in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (2.31.0)\n",
      "Requirement already satisfied: aiohttp>=3.7 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (3.9.3)\n",
      "Requirement already satisfied: aiohttp-cors in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (0.7.0)\n",
      "Requirement already satisfied: colorful in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (0.5.6)\n",
      "Requirement already satisfied: py-spy>=0.2.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (0.3.14)\n",
      "Requirement already satisfied: opencensus in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (0.11.4)\n",
      "Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (2.5.3)\n",
      "Requirement already satisfied: prometheus-client>=0.7.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (0.14.1)\n",
      "Requirement already satisfied: smart-open in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (7.0.4)\n",
      "Requirement already satisfied: virtualenv!=20.21.1,>=20.0.24 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (20.25.1)\n",
      "Requirement already satisfied: grpcio>=1.42.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[default]) (1.62.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from aiohttp>=3.7->ray[default]) (23.1.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /home/jtb/anaconda3/lib/python3.10/site-packages (from aiohttp>=3.7->ray[default]) (6.0.5)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from aiohttp>=3.7->ray[default]) (1.9.4)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from aiohttp>=3.7->ray[default]) (4.0.3)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3->ray[default]) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.14.6 in /home/jtb/anaconda3/lib/python3.10/site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3->ray[default]) (2.14.6)\n",
      "Requirement already satisfied: typing-extensions>=4.6.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3->ray[default]) (4.9.0)\n",
      "Requirement already satisfied: distlib<1,>=0.3.7 in /home/jtb/anaconda3/lib/python3.10/site-packages (from virtualenv!=20.21.1,>=20.0.24->ray[default]) (0.3.8)\n",
      "Requirement already satisfied: platformdirs<5,>=3.9.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from virtualenv!=20.21.1,>=20.0.24->ray[default]) (3.10.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/jtb/anaconda3/lib/python3.10/site-packages (from jsonschema->ray[default]) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /home/jtb/anaconda3/lib/python3.10/site-packages (from jsonschema->ray[default]) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from jsonschema->ray[default]) (0.10.6)\n",
      "Requirement already satisfied: opencensus-context>=0.1.3 in /home/jtb/anaconda3/lib/python3.10/site-packages (from opencensus->ray[default]) (0.1.3)\n",
      "Requirement already satisfied: six~=1.16 in /home/jtb/anaconda3/lib/python3.10/site-packages (from opencensus->ray[default]) (1.16.0)\n",
      "Requirement already satisfied: google-api-core<3.0.0,>=1.0.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from opencensus->ray[default]) (2.18.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/jtb/anaconda3/lib/python3.10/site-packages (from requests->ray[default]) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/jtb/anaconda3/lib/python3.10/site-packages (from requests->ray[default]) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from requests->ray[default]) (2.1.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/jtb/anaconda3/lib/python3.10/site-packages (from requests->ray[default]) (2024.2.2)\n",
      "Requirement already satisfied: wrapt in /home/jtb/anaconda3/lib/python3.10/site-packages (from smart-open->ray[default]) (1.16.0)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /home/jtb/anaconda3/lib/python3.10/site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (1.63.0)\n",
      "Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /home/jtb/anaconda3/lib/python3.10/site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (1.23.0)\n",
      "Requirement already satisfied: google-auth<3.0.dev0,>=2.14.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (2.29.0)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (5.3.3)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (0.4.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /home/jtb/anaconda3/lib/python3.10/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (4.9)\n",
      "Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /home/jtb/anaconda3/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.dev0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]) (0.6.0)\n",
      "Requirement already satisfied: ray[train] in /home/jtb/anaconda3/lib/python3.10/site-packages (2.10.0)\n",
      "Requirement already satisfied: click>=7.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[train]) (8.1.7)\n",
      "Requirement already satisfied: filelock in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[train]) (3.13.1)\n",
      "Requirement already satisfied: jsonschema in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[train]) (4.19.2)\n",
      "Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[train]) (1.0.8)\n",
      "Requirement already satisfied: packaging in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[train]) (23.2)\n",
      "Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[train]) (4.25.3)\n",
      "Requirement already satisfied: pyyaml in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[train]) (6.0.1)\n",
      "Requirement already satisfied: aiosignal in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[train]) (1.3.1)\n",
      "Requirement already satisfied: frozenlist in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[train]) (1.4.1)\n",
      "Requirement already satisfied: requests in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[train]) (2.31.0)\n",
      "Requirement already satisfied: pandas in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[train]) (2.2.1)\n",
      "Requirement already satisfied: tensorboardX>=1.9 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[train]) (2.6.2.2)\n",
      "Requirement already satisfied: pyarrow>=6.0.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[train]) (15.0.2)\n",
      "Requirement already satisfied: fsspec in /home/jtb/anaconda3/lib/python3.10/site-packages (from ray[train]) (2024.3.1)\n",
      "Requirement already satisfied: numpy<2,>=1.16.6 in /home/jtb/.local/lib/python3.10/site-packages (from pyarrow>=6.0.1->ray[train]) (1.24.1)\n",
      "Requirement already satisfied: attrs>=22.2.0 in /home/jtb/anaconda3/lib/python3.10/site-packages (from jsonschema->ray[train]) (23.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/jtb/anaconda3/lib/python3.10/site-packages (from jsonschema->ray[train]) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /home/jtb/anaconda3/lib/python3.10/site-packages (from jsonschema->ray[train]) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from jsonschema->ray[train]) (0.10.6)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /home/jtb/anaconda3/lib/python3.10/site-packages (from pandas->ray[train]) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from pandas->ray[train]) (2023.3.post1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /home/jtb/anaconda3/lib/python3.10/site-packages (from pandas->ray[train]) (2024.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/jtb/anaconda3/lib/python3.10/site-packages (from requests->ray[train]) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/jtb/anaconda3/lib/python3.10/site-packages (from requests->ray[train]) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from requests->ray[train]) (2.1.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/jtb/anaconda3/lib/python3.10/site-packages (from requests->ray[train]) (2024.2.2)\n",
      "Requirement already satisfied: six>=1.5 in /home/jtb/anaconda3/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->ray[train]) (1.16.0)\n",
      "Requirement already satisfied: pandas in /home/jtb/anaconda3/lib/python3.10/site-packages (2.2.1)\n",
      "Requirement already satisfied: numpy<2,>=1.22.4 in /home/jtb/.local/lib/python3.10/site-packages (from pandas) (1.24.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /home/jtb/anaconda3/lib/python3.10/site-packages (from pandas) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /home/jtb/anaconda3/lib/python3.10/site-packages (from pandas) (2023.3.post1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /home/jtb/anaconda3/lib/python3.10/site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: six>=1.5 in /home/jtb/anaconda3/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install \"torchmetrics>=0.9\" \"pytorch_lightning>=1.6\"\n",
    "!pip install torchvision\n",
    "!pip install ray\n",
    "!pip install \"ray[default]\"\n",
    "!pip install \"ray[train]\"\n",
    "!pip install pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import numpy as np\n",
    "import random\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "from filelock import FileLock\n",
    "from torch.utils.data import DataLoader, random_split, Subset\n",
    "from torchmetrics import Accuracy\n",
    "from torchvision.datasets import MNIST\n",
    "from torchvision import transforms\n",
    "\n",
    "import pytorch_lightning as pl\n",
    "from pytorch_lightning import trainer\n",
    "from pytorch_lightning.loggers.csv_logs import CSVLogger\n",
    "\n",
    "import ray\n",
    "from ray import train"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Prepare a dataset and module\n",
    "\n",
    "The Pytorch Lightning Trainer takes either `torch.utils.data.DataLoader` or `pl.LightningDataModule` as data inputs. You can continue using them without any changes with Ray Train. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "class MNISTDataModule(pl.LightningDataModule):\n",
    "    def __init__(self, batch_size=100):\n",
    "        super().__init__()\n",
    "        self.data_dir = os.getcwd()\n",
    "        self.batch_size = batch_size\n",
    "        self.transform = transforms.Compose(\n",
    "            [transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))]\n",
    "        )\n",
    "\n",
    "    def setup(self, stage=None):\n",
    "        with FileLock(f\"{self.data_dir}.lock\"):\n",
    "            mnist = MNIST(\n",
    "                self.data_dir, train=True, download=True, transform=self.transform\n",
    "            )\n",
    "\n",
    "            # Split data into train and val sets\n",
    "            self.mnist_train, self.mnist_val = random_split(mnist, [55000, 5000])\n",
    "\n",
    "    def train_dataloader(self):\n",
    "        return DataLoader(self.mnist_train, batch_size=self.batch_size, num_workers=4)\n",
    "\n",
    "    def val_dataloader(self):\n",
    "        return DataLoader(self.mnist_val, batch_size=self.batch_size, num_workers=4)\n",
    "\n",
    "    def test_dataloader(self):\n",
    "        with FileLock(f\"{self.data_dir}.lock\"):\n",
    "            self.mnist_test = MNIST(\n",
    "                self.data_dir, train=False, download=True, transform=self.transform\n",
    "            )\n",
    "        return DataLoader(self.mnist_test, batch_size=self.batch_size, num_workers=4)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Next, define a simple multi-layer perception as the subclass of `pl.LightningModule`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "class MNISTClassifier(pl.LightningModule):\n",
    "    def __init__(self, lr=1e-3, feature_dim=128):\n",
    "        torch.manual_seed(421)\n",
    "        super(MNISTClassifier, self).__init__()\n",
    "        self.save_hyperparameters()\n",
    "\n",
    "        self.linear_relu_stack = nn.Sequential(\n",
    "            nn.Linear(28 * 28, feature_dim),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(feature_dim, 10),\n",
    "            nn.ReLU(),\n",
    "        )\n",
    "        self.lr = lr\n",
    "        self.accuracy = Accuracy(task=\"multiclass\", num_classes=10, top_k=1)\n",
    "        self.eval_loss = []\n",
    "        self.eval_accuracy = []\n",
    "        self.test_accuracy = []\n",
    "        pl.seed_everything(888)\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = x.view(-1, 28 * 28)\n",
    "        x = self.linear_relu_stack(x)\n",
    "        return x\n",
    "\n",
    "    def training_step(self, batch, batch_idx):\n",
    "        x, y = batch\n",
    "        y_hat = self(x)\n",
    "        loss = torch.nn.functional.cross_entropy(y_hat, y)\n",
    "        self.log(\"train_loss\", loss)\n",
    "        return loss\n",
    "\n",
    "    def validation_step(self, val_batch, batch_idx):\n",
    "        loss, acc = self._shared_eval(val_batch)\n",
    "        self.log(\"val_accuracy\", acc)\n",
    "        self.eval_loss.append(loss)\n",
    "        self.eval_accuracy.append(acc)\n",
    "        return {\"val_loss\": loss, \"val_accuracy\": acc}\n",
    "\n",
    "    def test_step(self, test_batch, batch_idx):\n",
    "        loss, acc = self._shared_eval(test_batch)\n",
    "        self.test_accuracy.append(acc)\n",
    "        self.log(\"test_accuracy\", acc, sync_dist=True, on_epoch=True)\n",
    "        return {\"test_loss\": loss, \"test_accuracy\": acc}\n",
    "\n",
    "    def _shared_eval(self, batch):\n",
    "        x, y = batch\n",
    "        logits = self.forward(x)\n",
    "        loss = F.nll_loss(logits, y)\n",
    "        acc = self.accuracy(logits, y)\n",
    "        return loss, acc\n",
    "\n",
    "    def on_validation_epoch_end(self):\n",
    "        avg_loss = torch.stack(self.eval_loss).mean()\n",
    "        avg_acc = torch.stack(self.eval_accuracy).mean()\n",
    "        self.log(\"val_loss\", avg_loss, sync_dist=True)\n",
    "        self.log(\"val_accuracy\", avg_acc, sync_dist=True)\n",
    "        self.eval_loss.clear()\n",
    "        self.eval_accuracy.clear()\n",
    "    \n",
    "    def configure_optimizers(self):\n",
    "        optimizer = torch.optim.Adam(self.parameters(), lr=self.lr)\n",
    "        return optimizer"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "You don't need to modify the definition of the PyTorch Lightning model or datamodule."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Define a training function\n",
    "\n",
    "This code defines a {ref}`training function <train-overview-training-function>` for each worker. Comparing the training function with the original PyTorch Lightning code, notice three main differences:\n",
    "\n",
    "- Distributed strategy: Use {class}`RayDDPStrategy <ray.train.lightning.RayDDPStrategy>`.\n",
    "- Cluster environment: Use {class}`RayLightningEnvironment <ray.train.lightning.RayLightningEnvironment>`.\n",
    "- Parallel devices: Always set to `devices=\"auto\"` to use all available devices configured by ``TorchTrainer``.\n",
    "\n",
    "See {ref}`Getting Started with PyTorch Lightning <train-pytorch-lightning>` for more information.\n",
    "\n",
    "\n",
    "For checkpoint reporting, Ray Train provides a minimal {class}`RayTrainReportCallback <ray.train.lightning.RayTrainReportCallback>` class that reports metrics and checkpoints at the end of each train epoch. For more complex checkpoint logic, implement custom callbacks. See {ref}`Saving and Loading Checkpoint <train-checkpointing>`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "use_gpu = True # Set to False if you want to run without GPUs\n",
    "num_workers = 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pytorch_lightning as pl\n",
    "from ray.train import RunConfig, ScalingConfig, CheckpointConfig\n",
    "from ray.train.torch import TorchTrainer\n",
    "from ray.train.lightning import (\n",
    "    RayDDPStrategy,\n",
    "    RayLightningEnvironment,\n",
    "    RayTrainReportCallback,\n",
    "    prepare_trainer,\n",
    ")\n",
    "\n",
    "def train_func_per_worker():\n",
    "    model = MNISTClassifier(lr=1e-3, feature_dim=128)\n",
    "    datamodule = MNISTDataModule(batch_size=128)\n",
    "\n",
    "    trainer = pl.Trainer(\n",
    "        devices=\"auto\",\n",
    "        strategy=RayDDPStrategy(),\n",
    "        plugins=[RayLightningEnvironment()],\n",
    "        callbacks=[RayTrainReportCallback()],\n",
    "        max_epochs=10,\n",
    "        accelerator=\"gpu\" if use_gpu else \"cpu\",\n",
    "        log_every_n_steps=100,\n",
    "        logger=CSVLogger(\"logs\"),\n",
    "    )\n",
    "    \n",
    "    trainer = prepare_trainer(trainer)\n",
    "    \n",
    "    # Train model\n",
    "    trainer.fit(model, datamodule=datamodule)\n",
    "\n",
    "    # Evaluation on the test dataset\n",
    "    trainer.test(model, datamodule=datamodule)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Now put everything together:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "scaling_config = ScalingConfig(num_workers=num_workers, use_gpu=use_gpu)\n",
    "\n",
    "run_config = RunConfig(\n",
    "    name=\"ptl-mnist-example\",\n",
    "    storage_path=\"/tmp/ray_results\",\n",
    "    checkpoint_config=CheckpointConfig(\n",
    "        num_to_keep=3,\n",
    "        checkpoint_score_attribute=\"val_accuracy\",\n",
    "        checkpoint_score_order=\"max\",\n",
    "    ),\n",
    ")\n",
    "\n",
    "trainer = TorchTrainer(\n",
    "    train_func_per_worker,\n",
    "    scaling_config=scaling_config,\n",
    "    run_config=run_config,\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Now fit your trainer:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "jupyter": {
     "source_hidden": true
    }
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div class=\"tuneStatus\">\n",
       "  <div style=\"display: flex;flex-direction: row\">\n",
       "    <div style=\"display: flex;flex-direction: column;\">\n",
       "      <h3>Tune Status</h3>\n",
       "      <table>\n",
       "<tbody>\n",
       "<tr><td>Current time:</td><td>2024-04-06 10:55:10</td></tr>\n",
       "<tr><td>Running for: </td><td>00:00:05.56        </td></tr>\n",
       "<tr><td>Memory:      </td><td>7.9/31.1 GiB       </td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "    <div class=\"systemInfo\">\n",
       "      <h3>System Info</h3>\n",
       "      Using FIFO scheduling algorithm.<br>Logical resource usage: 1.0/20 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:P2200)\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "<div class=\"messages\">\n",
       "  <h3>Messages</h3>\n",
       "  \n",
       "  \n",
       "  Number of errored trials: 1<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name              </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                                                                  </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>TorchTrainer_a72f0_00000</td><td style=\"text-align: right;\">           1</td><td>/tmp/ray/session_2024-04-06_10-55-02_514710_194748/artifacts/2024-04-06_10-55-05/ptl-mnist-example/driver_artifacts/TorchTrainer_a72f0_00000_0_2024-04-06_10-55-05/error.txt</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "</div>\n",
       "<style>\n",
       ".messages {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  padding-left: 1em;\n",
       "  overflow-y: auto;\n",
       "}\n",
       ".messages h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n",
       "\n",
       "  </div>\n",
       "  <div class=\"hDivider\"></div>\n",
       "  <div class=\"trialStatus\">\n",
       "    <h3>Trial Status</h3>\n",
       "    <table>\n",
       "<thead>\n",
       "<tr><th>Trial name              </th><th>status  </th><th>loc                 </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>TorchTrainer_a72f0_00000</td><td>ERROR   </td><td>192.168.50.60:196089</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "  </div>\n",
       "</div>\n",
       "<style>\n",
       ".tuneStatus {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "}\n",
       ".tuneStatus .systemInfo {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus td {\n",
       "  white-space: nowrap;\n",
       "}\n",
       ".tuneStatus .trialStatus {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".tuneStatus .hDivider {\n",
       "  border-bottom-width: var(--jp-border-width);\n",
       "  border-bottom-color: var(--jp-border-color0);\n",
       "  border-bottom-style: solid;\n",
       "}\n",
       ".tuneStatus .vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(RayTrainWorker pid=196152)\u001b[0m Setting up process group for: env:// [rank=0, world_size=1]\n",
      "\u001b[36m(RayTrainWorker pid=196152)\u001b[0m [W CUDAFunctions.cpp:108] Warning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (function operator())\n",
      "2024-04-06 10:55:10,658\tERROR tune_controller.py:1332 -- Trial task failed for trial TorchTrainer_a72f0_00000\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/_private/worker.py\", line 2667, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/_private/worker.py\", line 864, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::_Inner.train()\u001b[39m (pid=196089, ip=192.168.50.60, actor_id=05919c44a596095f4d3c82f501000000, repr=TorchTrainer)\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/tune/trainable/trainable.py\", line 334, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/air/_internal/util.py\", line 88, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py\", line 53, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/base_trainer.py\", line 793, in _trainable_func\n",
      "    super()._trainable_func(self._merged_config)\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py\", line 261, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/base_trainer.py\", line 107, in _train_coordinator_fn\n",
      "    trainer.training_loop()\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/data_parallel_trainer.py\", line 449, in training_loop\n",
      "    backend_executor.start()\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/_internal/backend_executor.py\", line 187, in start\n",
      "    self._backend.on_start(self.worker_group, self._backend_config)\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/torch/config.py\", line 193, in on_start\n",
      "    ray.get(setup_futures)\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::_RayTrainWorker__execute._setup_torch_process_group()\u001b[39m (pid=196152, ip=192.168.50.60, actor_id=1530b6b85889e4c5206cfa8f01000000, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x76d4bb573e50>)\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/_internal/worker_group.py\", line 33, in __execute\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/_internal/worker_group.py\", line 30, in __execute\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/torch/config.py\", line 108, in _setup_torch_process_group\n",
      "    dist.init_process_group(\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/torch/distributed/c10d_logger.py\", line 86, in wrapper\n",
      "    func_return = func(*args, **kwargs)\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py\", line 1184, in init_process_group\n",
      "    default_pg, _ = _new_process_group_helper(\n",
      "  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py\", line 1339, in _new_process_group_helper\n",
      "    backend_class = ProcessGroupNCCL(\n",
      "ValueError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!\n",
      "2024-04-06 10:55:10,670\tINFO tune.py:1016 -- Wrote the latest version of all result files and experiment state to '/tmp/ray_results/ptl-mnist-example' in 0.0053s.\n",
      "2024-04-06 10:55:10,679\tERROR tune.py:1044 -- Trials did not complete: [TorchTrainer_a72f0_00000]\n",
      "2024-04-06 10:55:10,680\tINFO tune.py:1048 -- Total run time: 5.59 seconds (5.56 seconds for the tuning loop).\n"
     ]
    },
    {
     "ename": "TrainingFailedError",
     "evalue": "The Ray Train run failed. Please inspect the previous error messages for a cause. After fixing the issue (assuming that the error is not caused by your own application logic, but rather an error such as OOM), you can restart the run from scratch or continue this run.\nTo continue this run, you can use: `trainer = TorchTrainer.restore(\"/tmp/ray_results/ptl-mnist-example\")`.\nTo start a new run that will retry on training failures, set `train.RunConfig(failure_config=train.FailureConfig(max_failures))` in the Trainer's `run_config` with `max_failures > 0`, or `max_failures = -1` for unlimited retries.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRayTaskError(ValueError)\u001b[0m                  Traceback (most recent call last)",
      "\u001b[0;31mRayTaskError(ValueError)\u001b[0m: \u001b[36mray::_Inner.train()\u001b[39m (pid=196089, ip=192.168.50.60, actor_id=05919c44a596095f4d3c82f501000000, repr=TorchTrainer)\n  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/tune/trainable/trainable.py\", line 334, in train\n    raise skipped from exception_cause(skipped)\n  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/air/_internal/util.py\", line 88, in run\n    self._ret = self._target(*self._args, **self._kwargs)\n  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py\", line 53, in <lambda>\n    training_func=lambda: self._trainable_func(self.config),\n  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/base_trainer.py\", line 793, in _trainable_func\n    super()._trainable_func(self._merged_config)\n  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py\", line 261, in _trainable_func\n    output = fn()\n  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/base_trainer.py\", line 107, in _train_coordinator_fn\n    trainer.training_loop()\n  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/data_parallel_trainer.py\", line 449, in training_loop\n    backend_executor.start()\n  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/_internal/backend_executor.py\", line 187, in start\n    self._backend.on_start(self.worker_group, self._backend_config)\n  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/torch/config.py\", line 193, in on_start\n    ray.get(setup_futures)\nray.exceptions.RayTaskError(ValueError): \u001b[36mray::_RayTrainWorker__execute._setup_torch_process_group()\u001b[39m (pid=196152, ip=192.168.50.60, actor_id=1530b6b85889e4c5206cfa8f01000000, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x76d4bb573e50>)\n  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/_internal/worker_group.py\", line 33, in __execute\n    raise skipped from exception_cause(skipped)\n  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/_internal/worker_group.py\", line 30, in __execute\n    return func(*args, **kwargs)\n  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/ray/train/torch/config.py\", line 108, in _setup_torch_process_group\n    dist.init_process_group(\n  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/torch/distributed/c10d_logger.py\", line 86, in wrapper\n    func_return = func(*args, **kwargs)\n  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py\", line 1184, in init_process_group\n    default_pg, _ = _new_process_group_helper(\n  File \"/home/jtb/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py\", line 1339, in _new_process_group_helper\n    backend_class = ProcessGroupNCCL(\nValueError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mTrainingFailedError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[8], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m result \u001b[38;5;241m=\u001b[39m \u001b[43mtrainer\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.10/site-packages/ray/train/base_trainer.py:638\u001b[0m, in \u001b[0;36mBaseTrainer.fit\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    634\u001b[0m result \u001b[38;5;241m=\u001b[39m result_grid[\u001b[38;5;241m0\u001b[39m]\n\u001b[1;32m    635\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m result\u001b[38;5;241m.\u001b[39merror:\n\u001b[1;32m    636\u001b[0m     \u001b[38;5;66;03m# Raise trainable errors to the user with a message to restore\u001b[39;00m\n\u001b[1;32m    637\u001b[0m     \u001b[38;5;66;03m# or configure `FailureConfig` in a new run.\u001b[39;00m\n\u001b[0;32m--> 638\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m TrainingFailedError(\n\u001b[1;32m    639\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mjoin([restore_msg, TrainingFailedError\u001b[38;5;241m.\u001b[39m_FAILURE_CONFIG_MSG])\n\u001b[1;32m    640\u001b[0m     ) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mresult\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01merror\u001b[39;00m\n\u001b[1;32m    641\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m result\n",
      "\u001b[0;31mTrainingFailedError\u001b[0m: The Ray Train run failed. Please inspect the previous error messages for a cause. After fixing the issue (assuming that the error is not caused by your own application logic, but rather an error such as OOM), you can restart the run from scratch or continue this run.\nTo continue this run, you can use: `trainer = TorchTrainer.restore(\"/tmp/ray_results/ptl-mnist-example\")`.\nTo start a new run that will retry on training failures, set `train.RunConfig(failure_config=train.FailureConfig(max_failures))` in the Trainer's `run_config` with `max_failures > 0`, or `max_failures = -1` for unlimited retries."
     ]
    }
   ],
   "source": [
    "result = trainer.fit()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Check training results and checkpoints"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Validation Accuracy: \", result.metrics[\"val_accuracy\"])\n",
    "print(\"Trial Directory: \", result.path)\n",
    "print(sorted(os.listdir(result.path)))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Ray Train saved three checkpoints(`checkpoint_000007`, `checkpoint_000008`, `checkpoint_000009`) in the trial directory. The following code retrieves the latest checkpoint from the fit results and loads it back into the model.\n",
    "\n",
    "If you lost the in-memory result object, you can restore the model from the checkpoint file. The checkpoint path is: `/tmp/ray_results/ptl-mnist-example/TorchTrainer_eb925_00000_0_2023-08-07_23-15-06/checkpoint_000009/checkpoint.ckpt`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "checkpoint = result.checkpoint\n",
    "\n",
    "with checkpoint.as_directory() as ckpt_dir:\n",
    "    best_model = MNISTClassifier.load_from_checkpoint(f\"{ckpt_dir}/checkpoint.ckpt\")\n",
    "\n",
    "best_model"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## See also\n",
    "\n",
    "* {ref}`Getting Started with PyTorch Lightning <train-pytorch-lightning>` for a tutorial on using Ray Train and PyTorch Lightning \n",
    "\n",
    "* {doc}`Ray Train Examples <../../examples>` for more use cases"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  },
  "orphan": true,
  "vscode": {
   "interpreter": {
    "hash": "a8c1140d108077f4faeb76b2438f85e4ed675f93d004359552883616a1acd54c"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
